apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: trunks-leo
  name: trunks-leo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trunks-leo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s-manifests/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/container-gw: "true"
        io.kompose.network/container-st: "true"
        io.kompose.service: trunks-leo
    spec:
      containers:
        - args:
            - --config
            - trunks.yaml
            - --acm
            - --qos
          image: trunks
          name: trunks-leo
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          tty: true
          volumeMounts:
            - mountPath: /trunks/trunks.yaml
              name: trunks-leo-cm0
              subPath: trunks.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: trunks.yaml
                path: trunks.yaml
            name: trunks-leo-cm0
          name: trunks-leo-cm0
